export const ADD_FAV = 'ADD_FAV'
export const REMOVE_FAV = 'REMOVE_FAV'

export const FORECAST_FETCH = 'FORECAST_FETCH'
export const FORECAST_FETCH_SUCCESS = 'FORECAST_FETCH_SUCCESS'
export const FORECAST_FETCH_ERROR = 'FORECAST_FETCH_ERROR'